services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MaxServ\Pool\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  MaxServ\Pool\DataProcessors\GameDataProcessor:
    public: true

  MaxServ\Pool\DataProcessors\PlayerDataProcessor:
    public: true